ENTER_DVCD_ENTRANCE = 10
ENTER_DVCD_EXIT = 11
ENTER_DVCD_REENTER = 12
ENTER_POINT = 50
TIME_POINT_PER_SECOND = 0.25 # 초 단위 환산 점수

BIG_ROOM_COMPANY = [5,6,7]
SMALL_ROOM_COMPANY = [8,9,13]
MIN_TIME_POINT_BIG = 120
MIN_TIME_POINT_SMALL = 45
MAX_TIME_POINT_BIG = 375
MAX_TIME_POINT_SMALL = 180

MAX_TOTAL_POINT = 3365 # 만점

# CMN_CD
QUIZ_DVCD_ROOM_QUIZ = 1
QUIZ_DVCD_SURVEY = 2
QUIZ_DVCD_NFC_ENTRANCE = 3
QUIZ_DVCD_NFC_EXIST_TIME = 4
QUIZ_DVCD_PHOTO = 14

QUIZ_SHEET_COL_INDEX_SCORE = 1
QUIZ_SHEET_COL_INDEX_ID = 3